repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--line-length=88]
#
#  # - repo: https://github.com/pre-commit/mirrors-flake8
#  #   rev: v7.1.0  # Use the latest version
#  #   hooks:
#  #     - id: flake8
#
#
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v3.0.0a5
#    hooks:
#      - id: pylint
