repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--line-length=88]
#
#  # - repo: https://github.com/pre-commit/mirrors-flake8
#  #   rev: v7.1.0  # Use the latest version
#  #   hooks:
#  #     - id: flake8
#
#
#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v3.0.0a5
#    hooks:
#      - id: pylint




# repos:
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.6.0
#     hooks:
#       - id: check-yaml
#       - id: check-toml
#       - id: check-json
#       - id: check-xml
#       - id: end-of-file-fixer
#       - id: trailing-whitespace
#       - id: check-docstring-first
#       - id: name-tests-test
#       - id: file-contents-sorter
#       - id: pretty-format-json
#         args: [ --autofix ]
#       - id: check-ast
#       - id: check-builtin-literals
#       - id: check-case-conflict
#       - id: check-executables-have-shebangs
#       - id: check-merge-conflict
#       - id: check-shebang-scripts-are-executable
#       - id: debug-statements
#       - id: detect-private-key
#       - id: no-commit-to-branch
#         args: [ '--branch', 'main' ]
#   - repo: https://github.com/python-jsonschema/check-jsonschema
#     rev: 0.28.6
#     hooks:
#       - id: check-github-workflows
#         args: ["--verbose"]
#       - id: check-renovate
#   - repo: https://github.com/compilerla/conventional-pre-commit
#     rev: v3.2.0
#     hooks:
#       - id: conventional-pre-commit
#         stages: [commit-msg]
#         args: []
#   - repo: https://github.com/psf/black
#     rev: 24.4.2
#     hooks:
#       - id: black
#         language_version: python3
#         args: [ '--config', 'pyproject.toml' ]
#   - repo: https://github.com/PyCQA/docformatter
#     rev: v1.7.5
#     hooks:
#       - id: docformatter
#         additional_dependencies: [ tomli ]
#         args: [ --in-place ]
#   - repo: https://github.com/PyCQA/autoflake
#     rev: v2.3.1
#     hooks:
#       - id: autoflake
#         args:
#           [
#             '--in-place',
#             '--remove-unused-variable',
#             '--remove-all-unused-imports',
#             '--expand-star-imports',
#             '--ignore-init-module-imports',
#           ]
#   - repo: https://github.com/PyCQA/isort
#     rev: 5.13.2
#     hooks:
#       - id: isort
#         args: [ '--settings-file', 'pyproject.toml' ]
#   - repo: https://github.com/asottile/pyupgrade
#     rev: v3.16.0
#     hooks:
#       - id: pyupgrade
#   - repo: https://github.com/codespell-project/codespell
#     rev: v2.3.0
#     hooks:
#       - id: codespell
#         additional_dependencies:
#           - tomli
#   - repo: https://github.com/abravalheri/validate-pyproject
#     rev: v0.18
#     hooks:
#       - id: validate-pyproject
#         # Optional extra validations from SchemaStore:
#         additional_dependencies: [ "validate-pyproject-schema-store[all]" ]
#   - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
#     rev: v2.13.0
#     hooks:
#       - id: pretty-format-toml
#         exclude: poetry.lock
#         args: [ --autofix ]