import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://192.168.56.114:8012/login/?next=/")
    page.get_by_placeholder("Username").click()
    page.get_by_placeholder("Username").fill("admin")
    page.get_by_placeholder("Username").press("Enter")
    page.get_by_placeholder("Password").fill("ortseam@2024")
    page.get_by_role("button", name="Sign in").click()
    page.get_by_role("link", name=" Release Management").click()
    page.get_by_role("link", name=" Test Case Management").click()
    page.locator("#tc_release").select_option("1.0")
    page.locator("#tc_program").select_option("SA_FDD")
    page.locator("#tc_feature").select_option("HO")
    page.get_by_role("textbox", name="Testcase title").click()
    page.get_by_role("textbox", name="Testcase title").fill("IntraDU inter frequency handover")
    page.get_by_role("textbox", name="Testcase title").press("Enter")
    page.get_by_role("textbox", name="Testcase goal").click()
    page.get_by_role("textbox", name="Testcase goal").fill("Perform intraDU ")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").fill("Perform IntraDU ")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowRight")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowRight")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowRight")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowRight")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowRight")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowRight")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowRight")
    page.get_by_role("textbox", name="Testcase goal").fill("Perform IntraDU handover from cell 1 to Cell 2")
    page.get_by_role("textbox", name="Description").click()
    page.get_by_role("textbox", name="Description").fill("")
    page.get_by_role("textbox", name="Testcase goal").click()
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").press("ArrowLeft")
    page.get_by_role("textbox", name="Testcase goal").fill("To perform IntraDU handover from cell 1 to Cell 2")
    page.get_by_role("textbox", name="Description").click()
    page.get_by_role("textbox", name="Description").fill("Validate if Intra DU handover is working fine without ue getting released")
    page.locator("#summary").click()
    page.get_by_role("button", name="Add Details").click()
    page.get_by_placeholder("NR RU").click()
    page.get_by_placeholder("NR RU").click()
    page.get_by_placeholder("NR RU").click()
    page.get_by_placeholder("NR RU").fill("2")
    page.get_by_placeholder("NR RU").click()
    page.get_by_placeholder("NR RU").dblclick()
    page.locator("#tc_priority").select_option("P0")
    page.get_by_label("Network status").uncheck()
    page.get_by_label("Network status").check()
    page.get_by_label("Cell Status").uncheck()
    page.get_by_label("Cell Status").check()
    page.get_by_text("Radio Status").dblclick()
    page.get_by_text("Interface Status").dblclick()
    page.get_by_role("button", name="Attach UE").click()
    page.get_by_role("button", name="Attach UE").click()
    page.get_by_role("button", name="Detach UE").click()
    page.get_by_role("button", name="Traffic").click()
    page.get_by_role("button", name="Start DL Ping").click()
    page.get_by_role("button", name="Start DL Ping").click()
    page.get_by_role("button", name="Feature").click()
    page.get_by_role("button", name="Feature").click()
    page.get_by_role("button", name="Perform IntraDU InterFreq HO").click()
    page.get_by_role("button", name="Common").click()
    page.get_by_role("button", name="Attach UE").click()
    page.get_by_role("button", name="Detach UE").click()
    page.get_by_role("button", name="Traffic").click()
    page.get_by_role("button", name="Start DL Ping").click()
    page.get_by_role("button", name="Start DL Ping").click()
    page.get_by_role("button", name="Start DL Ping").click()
    page.get_by_role("button", name="Verification").click()
    page.get_by_role("button", name="Verify IntraDU InterFreq HO").click()
    page.get_by_role("button", name="Utilities").click()
    page.get_by_role("button", name="Feature").click()
    page.get_by_role("button", name="Verification").click()
    page.get_by_role("button", name="Verify Attach").click()
    page.get_by_role("button", name="Verify Detach").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Confirm").click()
    page.get_by_role("button", name="Perform IntraDU InterFreq HO").click()
    page.get_by_role("form").locator("#initial_cell").fill("1")
    page.get_by_role("form").locator("#final_cell").click()
    page.get_by_role("form").locator("#final_cell").fill("2")
    page.get_by_role("textbox", name="db/sec").click()
    page.get_by_role("textbox", name="db/sec").fill("1")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Add").click()
    page.locator("#state_block_div").get_by_role("button", name="Attach UE").click()
    page.get_by_role("form").locator("#cell_id").click()
    page.get_by_role("form").locator("#cell_id").fill("1")
    page.get_by_role("form").locator("#rsrp").click()
    page.get_by_role("form").locator("#rsrp").fill("70")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Add").click()
    page.locator("#state_block_div").get_by_role("button", name="Detach UE").click()
    page.get_by_role("form").locator("#detach_type").select_option("UE Initiated")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Add").click()
    page.get_by_role("button", name="Start DL Ping").click()
    page.get_by_role("form").locator("#packet_count").click()
    page.get_by_role("form").locator("#packet_count").fill("100")
    page.get_by_role("form").locator("#interval").click()
    page.get_by_role("form").locator("#interval").fill("300")
    page.get_by_role("form").locator("#pkt_size").click()
    page.get_by_role("form").locator("#pkt_size").fill("1400")
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Add").click()
    page.get_by_role("button", name="Start DL Ping").click()
    page.get_by_text("×").click()
    page.get_by_role("button", name="Verify IntraDU InterFreq HO").click()
    page.get_by_role("button", name="Verify IntraDU InterFreq HO").dblclick()
    page.get_by_role("button", name="Verify Attach").click()
    page.get_by_role("button", name="Verify Detach").click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("link", name=" Test Plan Management").click()
    page.locator("#oneliner26").click()
    page.get_by_role("button", name="XLS").click()
    page.get_by_role("button", name="Word").click()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("button", name="Script").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
